on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.7.2'

      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile project
        run: mix compile

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: _build
          path: _build/

      - name: Upload dependencies
        uses: actions/upload-artifact@v1
        with:
          name: deps
          path: deps
  test:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup postgres database
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'cambiatus_test'
          postgresql user: 'postgres'
          postgresql password: '123123123'

      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: _build

      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: deps

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'

      - name: Run all tests
        run: mix test
  lint:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: _build

      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: deps

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'

      - name: Lint project
        run: mix credo
  publishImage:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    needs: [build, test, lint]
    steps:
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: _build

      - name: Set APP_NAME
        run: |
          echo ::set-env name=APP_NAME::$(grep 'app:' mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g')

      - name: Set APP_VSN
        run: |
          echo ::set-env name=APP_VSN::$(grep 'version:' mix.exs | cut -d '"' -f2)

      - name: Set BUILD
        run: |
          echo ::set-env name=BUILD::$(git rev-parse --short HEAD)

      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bespiral/backend
          build_args: APP_NAME=${{ env.APP_NAME }},APP_VSN=${{ env.APP_VSN }}
          tags: ${{ env.APP_VSN }}-${{ env.BUILD }},latest
        
