name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp: ['24.2']
        elixir: ['1.14.2']

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.2'
          elixir-version: '1.14.2'

      - run: sudo apt -y install exiftool
      - run: mix deps.get
      - run: mix format --check-formatted    
      # - run: mix do compile --warnings-as-errors --all warnings, format --check-formatted, credo --strict --only warning
      - run: mix sobelow --config 
      - run: mix test

