on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'cambiatus_test'
          postgresql user: 'postgres'
          postgresql password: ''
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'
      - run: mix deps.get
      - run: mix test
